dist: trusty
os:
  - linux
sudo: required
language: php
php:
  - 7.0
  - 7.1
before_script:
  # PHP.ini
  - phpenv config-add travis.php.ini
before_install:
  # LibCouchbase
  - sudo wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-2-amd64.deb
  - sudo dpkg -i couchbase-release-1.0-2-amd64.deb
  - sudo apt-get update
  - sudo apt-get install libcouchbase-dev build-essential zlib1g-dev
  - pecl install pcs-1.3.3
  - pecl install couchbase
  # Couchbase Server
  - sudo apt-get install libssl-dev
  - sudo wget "https://packages.couchbase.com/releases/4.6.1/couchbase-server-enterprise_4.6.1-ubuntu14.04_amd64.deb"
  - sudo dpkg -i couchbase-server-enterprise_4.6.1-ubuntu14.04_amd64.deb
  - sudo service couchbase-server start
  # Configure Couchbase
  - sleep 20
  - /opt/couchbase/bin/install/reloc.sh `pwd`
  - /opt/couchbase/bin/couchbase-server -- -noinput -detached
  - sleep 20
  - /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 -u couch -p couchbase --cluster-name='raise' --services=data,index,query --cluster-ramsize=2048 --cluster-index-ramsize=256
  # Composer
  - composer self-update
  - composer install --no-interaction
script:
  - cd install/
  - php install.php --user=couch --pass=couchbase --address=localhost --skip-configuration
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sudo shutdown -h 0
branches:
  only:
    - sbr
