version: "2"
services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - composer
    links:
      - raise
    depends_on:
      - raise
  couchbase:
    build:
      context: .
      dockerfile: couchbase.Dockerfile
    volumes:
      - ./couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    env_file:
      - .env
  composer:
    image: composer
    restart: 'no'
    volumes:
      - .:/app
    command: install --no-dev
  raise:
    restart: 'always'
    build:
      context: .
      dockerfile: raise.Dockerfile
    command: "bash /raise-init.sh"
    volumes_from:
      - composer
    depends_on:
      - composer
      - couchbase
    links:
      - couchbase