version: "2"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/raise-core
      - ./docker/nginx.conf:/etc/nginx/conf.d/raise.conf
    links:
      - raise
  couchbase:
    image: couchbase/server
    volumes:
      - ./couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
  composer:
    restart: 'no'
    image: composer:latest
    command: install
    volumes:
      - .:/raise-core
  raise:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/raise-core
    links:
      - composer