version: "2"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/usr/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/raise.conf
    links:
      - raise
    depends_on:
      - raise
  couchbase:
    mem_limit: 2G
    image: couchbase/server
    volumes:
      - ./couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
  composer:
    restart: 'no'
    working_dir: /usr/app
    image: composer:latest
    command: install
    volumes:
      - .:/usr/app
    depends_on:
      - raise
  raise:
    build:
      context: .
      dockerfile: Dockerfile.raise
    volumes:
      - .:/usr/app
    links:
      - couchbase
  install:
    build:
      context: .
      dockerfile: Dockerfile.install
    depends_on:
      - composer