version: "2"
services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - composer
    links:
      - raise
    depends_on:
      - raise
  couchbase:
    image: couchbase/server
    volumes:
      - ./couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
  composer:
    image: composer
    restart: 'no'
    volumes:
      - .:/app
    command: install --no-dev
  raise:
    restart: 'no'
    build:
      context: .
      dockerfile: Dockerfile
    command: "bash /app/raise-init.sh"
    volumes_from:
      - composer
    depends_on:
      - composer
      - couchbase
    links:
      - couchbase