version: "2.1"
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - raise
    links:
      - php
    depends_on:
      - php
  couchbase:
    mem_limit: 2G
    image: couchbase/server
    volumes:
      - ./couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
  composer:
    image: composer
    restart: 'no'
    volumes_from:
      - raise
    command: install --no-dev
  raise:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    links:
      - couchbase
  php:
    restart: 'always'
    image: php:7.2-fpm
    volumes_from:
      - raise