version: "2"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/usr/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/raise.conf
    links:
      - raise
    depends_on:
      - raise
  couchbase:
    mem_limit: 2G
    image: couchbase/server
    volumes:
      - ./couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    command: /opt/couchbase/bin/couchbase-cli cluster-init \
      -c localhost:8091 --cluster-username=couchbase --cluster-password=couchbase --cluster-name='raise' \
      --services=data,index,query --cluster-ramsize=1024 --cluster-index-ramsize=256
  raise:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    depends_on:
      - couchbase
    links:
      - couchbase